# Generated by Django 4.1.7 on 2023-05-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_sharing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filesharing',
            old_name='description',
            new_name='bucket_name',
        ),
        migrations.RemoveField(
            model_name='filesharing',
            name='document',
        ),
        migrations.AddField(
            model_name='filesharing',
            name='file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='filesharing',
            name='url',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='filesharing',
            name='username',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
