# Generated by Django 4.1.7 on 2023-05-30 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Bypass check."""

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("file_sharing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="filesharing",
            name="from_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="from_user",
                to="users.user",
            ),
        ),
        migrations.AddField(
            model_name="filesharing",
            name="to_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="to_user",
                to="users.user",
            ),
        ),
    ]
