# Generated by Django 4.1.7 on 2023-05-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_sharing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filesharing',
            name='document',
        ),
        migrations.AddField(
            model_name='filesharing',
            name='url',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
