# Generated by Django 4.1.7 on 2023-05-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_sharing', '0002_remove_filesharing_document_filesharing_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesharing',
            name='bucket_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
