# Generated by Django 4.1.7 on 2023-05-30 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Bypass check."""

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("file_sharing", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filesharing",
            name="from_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="from_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="filesharing",
            name="to_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="to_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="filesharing",
            name="url",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
