# Generated by Django 4.1.7 on 2023-05-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_sharing', '0004_rename_description_filesharing_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesharing',
            name='id',
            field=models.BigAutoField(auto_created=True, max_length=255, primary_key=True, serialize=False),
        ),
    ]
