# Generated by Django 4.1.7 on 2023-05-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_sharing', '0005_alter_filesharing_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesharing',
            name='url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
