# Generated by Django 4.1.7 on 2023-05-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_sharing', '0006_alter_filesharing_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesharing',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
