version: '3.7'

# Specify service used
services:
  # Main Database
  mysql-database:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=file_sharing
      - MYSQL_USER=file_sharing
      - MYSQL_PASSWORD=file_sharing # Remember to change this
    volumes:
      - mysql_volume:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 30s
      retries: 20
    expose:
      - "3306"

  minio:
    image: minio/minio:RELEASE.2023-03-24T21-41-23Z
    volumes:
      - minio-storage:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: admin # Remember to change this, this must be the same as .env in backend!
      MINIO_SECRET_KEY: password@123 # also this
    command: server /data --console-address ":9001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 10

  django-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: sfs2023.azurecr.io/django-image
    ports:
      - "2234:8000"
    depends_on:
      mysql-database:
        condition: service_healthy
      detection:
        condition: service_started
      chat-service:
        condition: service_started
      minio:
        condition: service_healthy

  detection:
    build:
      context: ./addons
      dockerfile: Dockerfile
    image: sfs2023.azurecr.io/detection-image
    ports:
      - "9087:9087"
  chat-service:
    build:
      context: ./chat_services
      dockerfile: Dockerfile
    image: sfs2023.azurecr.io/chat_service
    expose:
      - "23432"
    ports:
      - "3400:3400"

# Specify volume (keep on each reload)
volumes:
  mysql_volume:
  minio-storage: