# Generated by Django 4.1.7 on 2023-04-25 04:21


from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RSAPrivateKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.BigIntegerField()),
                ('e', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RSAPublicKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p', models.BigIntegerField()),
                ('q', models.BigIntegerField()),
                ('d', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.BinaryField(max_length=255)),
            ],
        ),
    ]
