# Generated by Django 4.1.7 on 2023-04-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys_handler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsaprivatekey',
            name='d',
            field=models.CharField(max_length=310),
        ),
        migrations.AlterField(
            model_name='rsaprivatekey',
            name='p',
            field=models.CharField(max_length=310),
        ),
        migrations.AlterField(
            model_name='rsaprivatekey',
            name='q',
            field=models.CharField(max_length=310),
        ),
        migrations.AlterField(
            model_name='rsapublickey',
            name='e',
            field=models.CharField(max_length=310),
        ),
        migrations.AlterField(
            model_name='rsapublickey',
            name='n',
            field=models.CharField(max_length=310),
        ),
    ]
