# Generated by Django 4.1.7 on 2023-04-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auth_user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, max_length=6)),
                ('is_superuser', models.SmallIntegerField()),
                ('username', models.CharField(max_length=150)),
                ('first_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.SmallIntegerField()),
                ('is_active', models.SmallIntegerField()),
                ('date_joined', models.DateTimeField(max_length=6)),
            ],
        ),
    ]
