version: '3.7'

# Specify service used
services:
  nginx:
    build: 
      context: .
      dockerfile: Dockerfile
    image: sfs2023.azurecr.io/minio-nginx
    ports:
      - "80:9090"
      - "8080:9091"
