apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\flutter\bin\kompose.exe convert --push-image-registry sfs2023.azurecr.io
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  type: LoadBalancer
  ports:
    - name: "80"
      port: 80
      targetPort: 9090
    - name: "8080"
      port: 8080
      targetPort: 9091
    - name: "8081"
      port: 8081
      targetPort: 9092
    - name: "8082"
      port: 8082
      targetPort: 9093
  selector:
    io.kompose.service: nginx
status:
  loadBalancer: {}
