# Generated by Django 4.1.7 on 2023-06-21 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend_request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='friend_code_token',
            field=models.CharField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='friend_code',
            field=models.CharField(max_length=254),
        ),
    ]
