# Generated by Django 4.1.7 on 2023-06-21 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("friend_request", "0004_friendlist"),
    ]

    operations = [
        migrations.RenameField(
            model_name="friendlist",
            old_name="friend_id",
            new_name="user_idA",
        ),
        migrations.RenameField(
            model_name="friendlist",
            old_name="user_id",
            new_name="user_idB",
        ),
    ]
