# Generated by Django 4.1.7 on 2023-04-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('email', models.CharField(max_length=254)),
                ('date_verify', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
